#!/bin/bash

set -u

# source ~/.bash_profile

if [ -z "${1:-}" ]; then
    echo "Usage: chocopy <COMMAND>" >&2
    exit 1
fi

IFS_backup=$IFS # バックアップしておく。
IFS=$'\n'  # 区切り文字を変更

_lines=(`$*`)

select _selected in ${_lines[@]}
do
 echo $_selected | pbcopy
 echo chocopy to "$_selected"
 break
done

IFS=$IFS_backup # 元に戻す。

exit 0
