#!/bin/bash

set -u

# source ~/.bash_profile

if [ -z "${1:-}" ]; then
    echo "Usage: chocopy <COMMAND>" >&2
    exit 1
fi

#_resultOfCommand=`$*`
#
##デバッグ用
#echo $_resultOfCommand
#

#_lines=('')

ls -al | read -a _lines

echo ${_lines[@]}

exit 0

#select _selected in `$* | while read line`
#do
# echo $_selected | pbcopy
# echo chocopy to "$_selected"
# break
#done
#
#exit 0
